# ========== 基本功能 ==========
input-ipc-server = "/tmp/mpvsocket"  # 启用 IPC 通信
keep-open = "always"                 # 播放结束后保持窗口不关闭
border = "no"                        # 移除窗口边框，适合嵌入式/无边框模式
force-window = "immediate"                 # 强制立刻显示窗口（即使没有找到视频解码器）

# ========== 字幕设置 ==========
sub-auto = "fuzzy"                   # 自动加载匹配字幕
slang = chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze,cn,tw

sub-font = "Microsoft Yahei"         # 使用雅黑字体
sub-font-size = 80                   # 小屏适中字体大小（像素）
sub-border-size = 2                  # 黑边更粗，增强对比
sub-color = "#FFFFFF"                # 柔和醒目的字幕颜色
sub-shadow-color = "#000000"
sub-shadow-offset = 10
sub-margin-y = 29                    # 离底边适中距离
sub-use-margins = yes                # 开启边缘留白

# ========== 字幕渲染优化 ==========
sub-blur = 0                         # 关闭模糊，防止模糊不清
sub-back-color = "#000000"

# ========== OSD（界面信息）设置 ==========
osd-font = "Maple Mono Light"         # OSD 字体使用等宽字体
osd-font-size = 82                   # 字体大小
osd-color = "#FFFFFF"
osd-shadow-offset=1                  # 阴影（可选）
osd-border-size = 5                  # 描边
osd-level = 1                        # 关闭默认 OSD（如进度条）

fullscreen=yes
osc=yes
vd-lavc-threads=4
msg-level=vd=info

hr-seek=yes
demuxer-max-bytes=25M
demuxer-max-back-bytes=25M
demuxer-readahead-secs=30
cache=yes
cache-pause=yes
cache-pause-wait=30
cache-pause-initial=no

vo=wlshm
hwdec=rkmpp-copy

correct-downscaling=yes
linear-upscaling=no
sigmoid-upscaling=yes
scale=ewa_lanczossharp
